# Generated by Django 5.1.3 on 2024-12-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_trainer',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
